### ISSUE TITLE
Cannot send atoms with ledger in chrome 

### ISSUE THREAD

**Issue by thiloo** [luniehq/lunie#2469]
**Describe the bug**
I am having difficulties sending transactions in Chrome. It is possible to log into Lunie with ledger and I can see my atoms, however sending transactions fails with status code 500.

This error doesn't occur with Opera Browser, there sending transactions works fine. 

**To Reproduce**
1. Go to lunie.io
2. Log into lunie with ledger
3. Prepare a transaction and click on send
4. Sign on ledger device

**Expected behavior**
Expects to send transaction. 

**Screenshots**
![image](https://user-images.githubusercontent.com/21267961/56550386-16a7e300-65b8-11e9-8f13-c3cbb9bae1fa.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 
**Additional context**
Note this error doesn't occur with Opera. So that is a quick fix in case you phase the same issue.

**Comment by faboweb** [comment]
Hey!
Could you try again. The sending request body has changed in the lastest Cosmos SDK update. This should be fixed now.

**Comment by thiloo** [comment]
@faboweb thanks, it's working now

**Comment by pimato** [comment]
@faboweb I still have the same issues with delegating via my ledger nano s and chrome: 

<img width="622" alt="Screenshot 2019-04-23 at 10 27 45" src="https://user-images.githubusercontent.com/5337809/56566248-78fde500-65b2-11e9-9184-e9bece60047e.png">

**Comment by jbibla** [comment]
@pimato can you clear the cache, refresh the browser, and try again? is your ledger firmware up to date - and are you using chrome?

**Comment by pimato** [comment]
@jbibla I´ve created my own issue here, https://github.com/luniehq/lunie/issues/2475

**Comment by jbibla** [comment]
i believe this issue has been resolved. please let us know if you encounter this issue again.
