### ISSUE TITLE
Error when withdrawing rewards

### ISSUE THREAD

**Issue by jws325** [luniehq/lunie#2713]
Withdrawal failed: Tx.GetMsgs() must return at least one message in list

**Comment by fedekunze** [comment]
Same happened to me

**Comment by jbibla** [comment]
thanks for reporting. we've merged a few PRs to fix this and there will be a couple more today. thanks!!

**Comment by jackzampolin** [comment]
Sounds like users are still experiencing this issue. It will do quite a bit to centralize stake if our supported tooling makes it difficult to delegate to multiple validators.
