### ISSUE TITLE
Extension not building: `Can't resolve /img/tutorials`

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4836]
Logs from the bug while trying to build extension:

```
ERROR in /home/ana/lunie/lunie/app/src/components/common/ModalTutorial.vue?vue&type=style&index=0&id=1b516cee&scoped=true&lang=css& (/home/ana/lunie/lunie/node_modules/css-loader/dist/cjs.js!/home/ana/lunie/lunie/node_modules/vue-loader/lib/loaders/stylePostLoader.js!/home/ana/lunie/lunie/node_modules/vue-loader/lib??vue-loader-options!/home/ana/lunie/lunie/app/src/components/common/ModalTutorial.vue?vue&type=style&index=0&id=1b516cee&scoped=true&lang=css&)
    Module build failed (from /home/ana/lunie/lunie/node_modules/css-loader/dist/cjs.js):
    Error: Can't resolve '/img/tutorials/bg-red.png' in '/home/ana/lunie/lunie/app/src/components/common'
        at /home/ana/lunie/lunie/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:209:21
        at /home/ana/lunie/lunie/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
        at eval (eval at create (/home/ana/lunie/lunie/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
        at /home/ana/lunie/lunie/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
        at /home/ana/lunie/lunie/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
        at eval (eval at create (/home/ana/lunie/lunie/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
        at /home/ana/lunie/lunie/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
        at eval (eval at create (/home/ana/lunie/lunie/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
        at /home/ana/lunie/lunie/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
        at /home/ana/lunie/lunie/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
        at eval (eval at create (/home/ana/lunie/lunie/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
        at /home/ana/lunie/lunie/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
        at eval (eval at create (/home/ana/lunie/lunie/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
        at /home/ana/lunie/lunie/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
        at eval (eval at create (/home/ana/lunie/lunie/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
        at /home/ana/lunie/lunie/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
        at eval (eval at create (/home/ana/lunie/lunie/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
        at /home/ana/lunie/lunie/node_modules/webpack/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:27:15
        at /home/ana/lunie/lunie/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15
        at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

**Comment by faboweb** [comment]
This is already fixed

**Comment by Bitcoinera** [comment]
:facepalm:

**Comment by Bitcoinera** [comment]
It is not fixed on develop. So developers cannot build extension

**Comment by Bitcoinera** [comment]
Also look at the changes with the node versions I had to make for the checks to pass
